on: gollum
name: Slack wiki test
jobs:
  slackNotification:
    name: Slack Wiki Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
          uses: actions/setup-go@v1
          with:
            go-version: 1.13
          id: go

      - uses: actions/checkout@v2
      - name: Build
            run: |
              go get -d -v
              go build -v .
